### ISSUE TITLE
Holes in print

### ISSUE THREAD

**Issue by Toylerrr** [just-trey/elegoo_neptune_2_CHEP_cura_profiles#1]
When using any of the profiles I seem to be getting holes in the walls.

Chep good profile:
![image](https://user-images.githubusercontent.com/4400902/131183885-16b2f0e6-69bc-413a-a8e7-d0a81220f5ab.png)

Elegoo normal profile:
![image](https://user-images.githubusercontent.com/4400902/131184064-686fa9dc-f51c-443e-ada0-6d775495cc64.png)

Any idea why?

**Comment by just-trey** [comment]
@Toylerrr you may be looking at a new setting in Cura on your preview called "starts". They made it white for some reason. Let me know if that is what you are seeing.

![Screenshot from 2021-08-27 22-51-33](https://user-images.githubusercontent.com/10281380/131204055-dc7b2059-29cd-48b0-98cb-2193c90f3de1.png)

Also I just pushed a new version out reverting most of my customizations. I was getting mixed results with some (especially Adapitve layers).  And I figured enabling experimental features is probably not a good idea to enable for a base set of configurations.

**Comment by just-trey** [comment]
closing issue as there is no response.
