### ISSUE TITLE
Update.

### ISSUE THREAD

**Issue by Justdigit** [just-trey/elegoo_neptune_2_CHEP_cura_profiles#3]
Hi thanks for the conversion... Any change you can update to the latest? (smooth)

**Comment by just-trey** [comment]
@Justdigit, sure. I have done limited testing on this, but they should work fine. If you have any problems feel free to open a new issue. The latest version has been merged to main. https://github.com/just-trey/elegoo_neptune_2_CHEP_cura_profiles
