### ISSUE TITLE
What do you set the printer to initially?

### ISSUE THREAD

**Issue by Demwunz** [just-trey/elegoo_neptune_2_CHEP_cura_profiles#5]
Since Cure doesn't have Neptune 2 as a default offline printer - what do you set initally?
I'm unable to import these as I've had to set it as Creality Ender-3 to begin with.

**Comment by Demwunz** [comment]
figured it out. doh!

**Comment by jeremiahverba** [comment]
what was the answer?  For us future noobs.

**Comment by just-trey** [comment]
https://github.com/Toylerrr/Elegoo-Neptune-Support
