### ISSUE TITLE
Updated CHEP 4.12 profile

### ISSUE THREAD

**Issue by quanennathaniel** [just-trey/elegoo_neptune_2_CHEP_cura_profiles#6]
Hello there’s a new CHEP 4.12 profile! Could you update it? Would also appreciate a tutorial on how you change the profiles from a Ender one to one that’s works with the Neptune 2. I can’t seem to do it!

**Comment by just-trey** [comment]
I'll write up some better  instructions when I have some time. In a nutshell you have to add a zip extension and unzip the files to edit them. You then have to change the settings for the printer type to fdmprinter and the quality settings to what fdmprinter allows. I can't recall what they are off the top of my head. But those are the edits I have to make.

**Comment by just-trey** [comment]
Oh profiles are updated

**Comment by just-trey** [comment]
Updated
