### ISSUE TITLE
Quality type 'fine' is not compatible with the current active machine definition 'creality_base'

### ISSUE THREAD

**Issue by ah3243** [just-trey/elegoo_neptune_2_CHEP_cura_profiles#8]
Hi,
I'm trying to import the profiles into ultimaker cura (4.13.1) and I'm getting messages saying "quality type 'fine' is not compatible with active machine definition 'creality_base'. I'm running cura on an m1 mac in case that's important and my printer is a neptune 2. 
thanks!

**Comment by just-trey** [comment]
@ah3243, that message indicates to me you are using the Ender configuration in cura (which is fine) but you should use original CHEP's profiles here: https://www.chepclub.com/cura-profiles.html  and they will work for you.
